version: '3'
services:
    qbittorrent:
        container_name: qbittorrent
        image: linuxserver/qbittorrent:latest
        restart: unless-stopped
        ports:
           - "8080:8080"
        volumes:
            - /home/plex/downloads:/downloads
            - /home/plex/qbittorrent/config:/config
            - /media/tvshows:/tv_shows
        environment:
            - TZ="America/Chicago"
            - PGID=1001
            - PUID=1001
